/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        health: {
          teal: '#14B8A6',
          cyan: '#06B6D4'
        },
        healthpro: {
          primary: '#005c55',
          'primary-container': '#0f766e',
          'on-primary': '#ffffff',
          'secondary-container': '#bde7eb',
          'on-secondary-container': '#41696d',
          surface: '#f7faf8',
          'surface-dim': '#d7dbd9',
          'surface-container-low': '#f1f4f3',
          'on-surface': '#181c1c',
          'on-surface-variant': '#3e4947',
          'outline-variant': '#bdc9c6',
          'primary-fixed': '#9cf2e8'
        },
        agro: {
          primary: '#005d42',
          'primary-container': '#047857',
          'on-primary': '#ffffff',
          'on-primary-container': '#9ffdd3',
          secondary: '#944a23',
          'secondary-container': '#fd9e70',
          'on-secondary': '#ffffff',
          'on-secondary-container': '#76340e',
          surface: '#f8f9ff',
          'surface-dim': '#d1dbec',
          'surface-container-low': '#eef4ff',
          'surface-container-lowest': '#ffffff',
          'on-surface': '#121c28',
          'on-surface-variant': '#3e4943',
          'outline-variant': '#bdc9c1',
          'surface-variant': '#d9e3f4',
          green: '#10B981',
          brown: '#92400E',
          cream: '#FEF3C7'
        },
        tech: {
          'primary-fixed': '#dae2fd',
          'tertiary-fixed-dim': '#ffb95f',
          'tertiary-container': '#2a1700',
          secondary: '#a73a00',
          'on-secondary': '#ffffff',
          'on-primary-fixed-variant': '#3f465c',
          'error-container': '#ffdad6',
          'surface-container': '#eaeef2',
          'tertiary-fixed': '#ffddb8',
          'secondary-container': '#fd651e',
          'inverse-surface': '#2c3134',
          'primary-container': '#131b2e',
          'on-tertiary': '#ffffff',
          'on-background': '#171c1f',
          tertiary: '#000000',
          'on-error': '#ffffff',
          'surface-container-highest': '#dfe3e7',
          'secondary-fixed-dim': '#ffb599',
          surface: '#f6fafe',
          'on-error-container': '#93000a',
          'on-surface-variant': '#45464d',
          'surface-dim': '#d6dade',
          'surface-container-high': '#e4e9ed',
          'inverse-primary': '#bec6e0',
          'on-surface': '#171c1f',
          'on-secondary-container': '#571a00',
          primary: '#000000',
          'primary-fixed-dim': '#bec6e0',
          'surface-tint': '#565e74',
          'surface-container-low': '#f0f4f8',
          'surface-container-lowest': '#ffffff',
          'on-primary-fixed': '#131b2e',
          'surface-variant': '#dfe3e7',
          'on-tertiary-container': '#b87500',
          background: '#f6fafe',
          'on-primary-container': '#7c839b',
          'secondary-fixed': '#ffdbce',
          'inverse-on-surface': '#edf1f5',
          'on-primary': '#ffffff',
          'on-tertiary-fixed': '#2a1700',
          'on-tertiary-fixed-variant': '#653e00',
          error: '#ba1a1a',
          'outline-variant': '#c6c6cd',
          outline: '#76777d',
          'on-secondary-fixed': '#370e00',
          'surface-bright': '#f6fafe',
          'on-secondary-fixed-variant': '#7f2b00',
          gray: '#374151',
          black: '#111827',
          orange: '#F97316',
          blue: '#3B82F6'
        },
        law: {
          navy: '#001F3F',
          burgundy: '#800020',
          gold: '#D4AF37'
        },
        biz: {
          blue: '#1E40AF',
          gold: '#FFD700'
        }
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Merriweather', 'serif'],
        mono: ['Courier New', 'monospace'],
      }
    },
  },
  plugins: [],
}
